# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[╭](lavender)\
$os\
$username\
[ ](fg:lavender)\
$directory\
$cmd_duration
[╰ ](fg:lavender)$character\
"""

right_format = """
$git_branch\
$time\
"""

palette = 'catppuccin_mocha'

# Inserts a blank line between shell prompts
add_newline = true

[character]
success_symbol = '[](bold green)'
error_symbol = '[](bold red)'

[os]
disabled = false
format = '[$symbol ]($style)'
style = 'bg:lavender fg:crust'

[os.symbols]
Windows = ""
Ubuntu = ""
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
disabled = false
format = '[$user]($style)'
style_user = 'bg:lavender fg:crust'
show_always = true

[time]
disabled = false
time_format = "%I:%M %p"
format = '[ $time]($style) '
use_12hr = true
style = 'fg:lavender'

[directory]
style = "fg:mauve"
format = "[$path]($style)"
home_symbol = '󰜥'
truncation_length = 3
truncation_symbol = " /"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Developer" = " "

[git_branch]
symbol = ""
style = "bold red"
format = "[$symbol $branch ]($style)"

[cmd_duration]
show_milliseconds = true
format = "[   in $duration ]($style)"
style = "bold lavender"
disabled = false
show_notifications = true
min_time_to_notify = 35000

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
